////APP
export const APP_GET_LANGUAGE = 'APP_GET_LANGUAGE';
export const MAKE_LOGIN = 'MAKE_LOGIN';
export const MAKE_LOGOUT = 'MAKE_LOGOUT';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';
export const START_SERVER_COMUNICATION = 'START_SERVER_COMUNICATION';
export const END_SERVER_COMUNICATION = 'END_SERVER_COMUNICATION';
export const SERVER_COMUNICATION_FAIL = 'SERVER_COMUNICATION_FAIL';
export const RESET_SERVER_ERROR = 'RESET_SERVER_ERROR';

////NEWS
export const GET_NEWS_LIST = 'GET_NEWS_LIST';
export const CHANGE_NEWS_LANGUAGE = 'CHANGE_NEWS_LANGUAGE';
export const GET_NEWS_DATA = 'GET_NEWS_DATA';
export const CHANGE_NEWS_DATA_LANGUAGE = 'CHANGE_NEWS_DATA_LANGUAGE';
export const ADD_NEWS_COMMENT = 'ADD_NEWS_COMMENT';

////HOMEPAGE
export const CHANGE_PRESENTATION_LANGUAGE = 'CHANGE_PRESENTATION_LANGUAGE';
export const GET_HOME_DATA = 'GET_HOME_DATA';