////APP
export const APP_GET_LANGUAGE = 'APP_GET_LANGUAGE';
export const START_SERVER_COMUNICATION = 'START_SERVER_COMUNICATION';
export const END_SERVER_COMUNICATION = 'END_SERVER_COMUNICATION';
export const SERVER_COMUNICATION_FAIL = 'SERVER_COMUNICATION_FAIL';
export const RESET_SERVER_ERROR = 'RESET_SERVER_ERROR';

////REGISTRATION
export const CHECK_USERNAME = 'CHECK_USERNAME';
export const MAKE_REGISTRATION = 'MAKE_REGISTRATION';
export const RESET_REGISTRATION = 'RESET_REGISTRATION';

////NEWS
export const GET_NEWS_LIST = 'GET_NEWS_LIST';
export const CHANGE_NEWS_LANGUAGE = 'CHANGE_NEWS_LANGUAGE';
export const GET_NEWS_DATA = 'GET_NEWS_DATA';
export const CHANGE_NEWS_DATA_LANGUAGE = 'CHANGE_NEWS_DATA_LANGUAGE';
export const ADD_NEWS_COMMENT = 'ADD_NEWS_COMMENT';
export const RESET_NEWS_DATA = 'RESET_NEWS_DATA';
export const RESET_NEWS_LIST = 'RESET_NEWS_LIST';

////HOMEPAGE
export const CHANGE_PRESENTATION_LANGUAGE = 'CHANGE_PRESENTATION_LANGUAGE';
export const GET_HOME_DATA = 'GET_HOME_DATA';
export const RESET_HOME_DATA = 'RESET_HOME_DATA';

////MY ACCOUNT
export const MAKE_LOGIN = 'MAKE_LOGIN';
export const MAKE_LOGOUT = 'MAKE_LOGOUT';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';
export const CHANGE_MYACCOUNT_NAME = 'CHANGE_MYACCOUNT_NAME';
export const RESET_MYACCOUNT_STATUS = 'RESET_MYACCOUNT_STATUS';
export const RESET_MYACCOUNT_SUCCSESS = 'RESET_MYACCOUNT_SUCCSESS';
export const MYACCOUNT_CHECK_OLD_PASSWORD = 'MYACCOUNT_CHECK_OLD_PASSWORD';
export const MYACCOUNT_CHANGE_PASSWORD = 'MYACCOUNT_CHANGE_PASSWORD';
export const MYACCOUNT_CHECK_PASSWORD = 'MYACCOUNT_CHECK_PASSWORD';
export const MYACCOUNT_CHECK_EMAIL = 'MYACCOUNT_CHECK_EMAIL';
export const MYACCOUNT_DISABLE_ACCOUNT = 'MYACCOUNT_DISABLE_ACCOUNT';
export const MYACCOUNT_ENABLE_ACCOUNT = 'MYACCOUNT_ENABLE_ACCOUNT';
export const MYACCOUNT_CLOSE_ACCOUNT = 'MYACCOUNT_CLOSE_ACCOUNT';