////APP
export const APP_GET_LANGUAGE = 'APP_GET_LANGUAGE';
export const MAKE_LOGIN = 'MAKE_LOGIN';
export const MAKE_LOGOUT = 'MAKE_LOGOUT';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';

////NEWS
export const GET_NEWS_LIST = 'GET_NEWS_LIST';
export const GET_NEWS_LIST_SHORT = 'GET_NEWS_LIST_SHORT';
export const CHANGE_NEWS_LANGUAGE = 'CHANGE_NEWS_LANGUAGE';
export const GET_NEWS_DATA = 'GET_NEWS_DATA';
export const CHANGE_NEWS_DATA_LANGUAGE = 'CHANGE_NEWS_DATA_LANGUAGE';
export const ADD_NEWS_COMMENT = 'ADD_NEWS_COMMENT';

////HOMEPAGE
export const GET_PRESENTATION_DATA = 'GET_PRESENTATION_DATA';
export const CHANGE_PRESENTATION_LANGUAGE = 'CHANGE_PRESENTATION_LANGUAGE';
export const GET_HOME_IMAGE = 'GET_HOME_IMAGE';
